services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nw
    restart: unless-stopped
    depends_on:
      - root_server
      - about_server
      - projects_server

  root_server: 
    build: ./root/
    networks: 
      - nw
    restart: unless-stopped
    stop_grace_period: 1s

  about_server:
    build: ./about/
    networks:
      - nw
    restart: unless-stopped

  projects_server:
    build: ./projects/
    networks:
      - nw
    restart: unless-stopped

networks:
  nw:
    driver: bridge
