services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    networks:
      - nw
    restart: unless-stopped


  nextjs-about:
    build: ./nextjs-about/
    networks:
      - nw
    restart: unless-stopped

networks:
  nw:
    driver: bridge
