services:
  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nw
    restart: unless-stopped
    depends_on:
      - root_server
      - about_server
      - projects_server

  root_server: 
    build: ./root/
    image: dockerkristo/website_root:latest
    networks: 
      - nw
    restart: unless-stopped
    stop_grace_period: 1s

  about_server:
    build: ./about/
    image: dockerkristo/website_about:latest
    networks:
      - nw
    restart: unless-stopped

  projects_server:
    build: ./projects/
    image: dockerkristo/website_projects:latest
    networks:
      - nw
    restart: unless-stopped

  chess_server:
    build: ./chess/
    image: dockerkristo/website_chess:latest
    networks:
      - nw
    restart: unless-stopped

networks:
  nw:
    driver: bridge
